Vinventory Dupe Fix
AsYetUntitled/Framework pull request #620
Opened 2020-03-10 05:09 UTC by RoberioJr

Resolves #. 

#### Changes proposed in this pull request: 
- Fix the bug that allows you to duplicate virtual items using a vehicle or a box with the help of another player. (Opening the virtual inventory at the same time)

- [ ] I have tested my changes and corrected any errors found

2020-03-17 20:29 UTC, DomT602 requested changes
Just 2 small changes :)

2020-03-17 20:29 UTC, DomT602 commented on Altis_Life.Altis/core/vehicle/fn_openInventory.sqf
> +        if ((_this getVariable ["trunk_in_use_by",player]) != player) then {closeDialog 0; hint "Another player tried to open the inventory of that vehicle!"};
Could we add the hint to the stringtable?

2020-03-17 20:29 UTC, DomT602 commented on Altis_Life.Altis/core/vehicle/fn_openInventory.sqf
> +        (isNull (findDisplay 3500))
Can remove the outer brackets

2020-03-18 23:02 UTC, DomT602 commented on Altis_Life.Altis/core/vehicle/fn_openInventory.sqf
> +        if ((_this getVariable ["trunk_in_use_by",player]) != player) then {closeDialog 0; hint localize "STR_MISC_VehInvUse"};
Thanks for doing this, you do need to actually make the string in the stringtable though! If you need any help with that feel free to join the discord.

2020-03-18 23:05 UTC, DomT602 approved these changes
Looks good to me, just wanna check with someone else.

2020-03-19 20:21 UTC, RoberioJr commented
Ok!

2021-02-03 20:42 UTC, closed without merging